name: "SunGather"
version: "0.1.0"
slug: sungather
description: "Extract Sungrow data from local Inverter"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/bohdan-s/SunGather"
startup: application
ingress: true
ingress_port: 8099
boot: auto
discovery:
  - "mqtt"
services:
  - "mqtt:need"
map: 
  - share:rw
options: 
  host: 192.168.1.100
  timeout: 10
  scan_interval: 30
  connection: "modbus"
  smart_meter: True
  log_console: "INFO"
schema:
  host: str
  timeout: int(3,60)?
  scan_interval: int(5,600)?
  connection: "list(sungrow|modbus|http)"
  smart_meter: bool?
  log_console: "list(OFF|INFO|WARNING|ERROR|DEBUG)?"
configuration:
  host:
    name: "IP Address"
    description: "[Required] IP Address of the Inverter or Dongle"
  connection:
    name: "Connection Type"
    description: "[Required] Usually modbus, HTTP for WiNet-S Dongles, sungrow for some legacy models"
  smart_meter:
    name: "Smart Meter Install"
    description: "Set to true if inverter supports reading grind / house consumption (may not be needed for Hybrid models)"
panel_icon: mdi:SolarPowerVariant
init: false





